package com.b2ta.common.ai;

import com.b2ta.common.config.BedrockProperties;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.Builder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.Duration;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates candidate feedback snippets from the levels a TA selected and the evidence they
 * confirmed (Requirements 12.3, 12.6, 12.7).
 *
 * <p>The prompt is built only from the TA's own decisions: selected performance levels, awarded
 * points, and the passages they confirmed. The model is not asked to grade, and is not given the
 * submission text beyond the confirmed passages — a snippet that referenced something the TA had not
 * marked as evidence would be feedback the TA cannot defend.
 *
 * <p>Snippets are returned unsaved and labelled as AI-generated by the caller, so nothing reaches a
 * student without the TA accepting or editing it (Requirement 12.5).
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class CommentAssistant {

    private static final String SYSTEM_PROMPT = """
            You are a constructive feedback writing assistant for academic grading. Generate \
            specific, actionable feedback based on the rubric levels selected and the evidence \
            found. Do not invent evidence that is not provided. Do not restate the score. Write in \
            the second person, addressing the student.""";

    /** Shortest usable snippet (Requirement 12.3). */
    public static final int MIN_SNIPPET_LENGTH = 1;

    /** Longest snippet (Requirement 12.3). */
    public static final int MAX_SNIPPET_LENGTH = 1000;

    /** Most snippets returned per request (Requirement 12.3). */
    public static final int MAX_SNIPPETS = 5;

    private static final int MAX_OUTPUT_TOKENS = 2048;

    /** Confirmed passages are truncated in the prompt so one long passage cannot crowd out others. */
    private static final int MAX_PASSAGE_CHARS_IN_PROMPT = 600;

    private final BedrockJsonClient bedrock;
    private final BedrockProperties properties;

    /** One scored criterion, as input to snippet generation. */
    @Builder
    public record ScoredCriterion(String title,
                                  String selectedLevelLabel,
                                  String selectedLevelDescription,
                                  BigDecimal awardedPoints,
                                  BigDecimal maxPoints) {
    }

    /** One piece of confirmed evidence, as input to snippet generation. */
    @Builder
    public record Evidence(String criterionTitle, String passageText, String rationale) {
    }

    /**
     * Generates between 1 and {@link #MAX_SNIPPETS} snippets.
     *
     * @param scored   criteria with a selected level or an override; never empty (the caller blocks
     *                 the request when nothing is scored, per Requirement 12.8)
     * @param evidence confirmed matches, possibly empty
     * @return snippets, each 1-1000 characters
     * @throws BedrockUnavailableException when Bedrock fails or exceeds the 15-second budget
     */
    public List<String> suggest(List<ScoredCriterion> scored, List<Evidence> evidence) {
        JsonNode result = bedrock.invokeStructured(
                properties.getCommentModelId(),
                SYSTEM_PROMPT,
                buildPrompt(scored, evidence),
                responseSchema(),
                MAX_OUTPUT_TOKENS,
                Duration.ofSeconds(properties.getCommentTimeoutSeconds()));

        JsonNode snippets = result.path("snippets");
        List<String> cleaned = new ArrayList<>();
        if (snippets.isArray()) {
            for (JsonNode node : snippets) {
                String text = node.isTextual() ? node.asText() : node.path("text").asText("");
                text = text.strip();
                if (text.length() < MIN_SNIPPET_LENGTH) {
                    continue;
                }
                if (text.length() > MAX_SNIPPET_LENGTH) {
                    text = text.substring(0, MAX_SNIPPET_LENGTH);
                }
                cleaned.add(text);
                if (cleaned.size() == MAX_SNIPPETS) {
                    break;
                }
            }
        }

        if (cleaned.isEmpty()) {
            // Requirement 12.3 promises at least one snippet. An empty array is a failed generation,
            // not a valid answer, so it surfaces as a failure the TA can retry rather than as an
            // empty suggestion list that looks like the feature is broken.
            throw new BedrockUnavailableException(
                    "The comment assistant returned no usable suggestions", false, null);
        }
        return List.copyOf(cleaned);
    }

    private String buildPrompt(List<ScoredCriterion> scored, List<Evidence> evidence) {
        StringBuilder levels = new StringBuilder();
        for (ScoredCriterion criterion : scored) {
            levels.append("- ").append(criterion.title()).append(": ");
            levels.append(criterion.selectedLevelLabel() == null
                    ? "manual score" : criterion.selectedLevelLabel());
            if (criterion.awardedPoints() != null) {
                levels.append(" (").append(criterion.awardedPoints());
                if (criterion.maxPoints() != null) {
                    levels.append(" of ").append(criterion.maxPoints());
                }
                levels.append(" points)");
            }
            if (criterion.selectedLevelDescription() != null
                    && !criterion.selectedLevelDescription().isBlank()) {
                levels.append("\n  Level description: ")
                        .append(criterion.selectedLevelDescription());
            }
            levels.append('\n');
        }

        StringBuilder evidenceBlock = new StringBuilder();
        if (evidence.isEmpty()) {
            evidenceBlock.append("(No passages were confirmed as evidence.)\n");
        } else {
            for (Evidence item : evidence) {
                evidenceBlock.append("- Criterion: ").append(item.criterionTitle()).append('\n');
                evidenceBlock.append("  Passage: \"").append(truncate(item.passageText()))
                        .append("\"\n");
                if (item.rationale() != null && !item.rationale().isBlank()) {
                    evidenceBlock.append("  Why it matters: ").append(item.rationale()).append('\n');
                }
            }
        }

        return """
                ## Rubric Criteria and Selected Levels
                %s
                ## Confirmed Evidence
                %s
                ## Instructions
                Generate between 1 and %d feedback snippets, each between %d and %d characters, that:
                - reference specific strengths and areas for improvement drawn from the evidence above
                - are constructive and actionable
                - match the tone of academic feedback
                - can stand alone, so the grader can use any one of them independently

                Base every claim on the levels and evidence above. If the evidence does not support a \
                point, leave it out."""
                .formatted(levels.toString(), evidenceBlock.toString(),
                        MAX_SNIPPETS, MIN_SNIPPET_LENGTH, MAX_SNIPPET_LENGTH);
    }

    private String truncate(String passage) {
        if (passage == null) {
            return "";
        }
        String collapsed = passage.replaceAll("\\s+", " ").strip();
        return collapsed.length() <= MAX_PASSAGE_CHARS_IN_PROMPT
                ? collapsed
                : collapsed.substring(0, MAX_PASSAGE_CHARS_IN_PROMPT) + "...";
    }

    private Map<String, Object> responseSchema() {
        Map<String, Object> snippets = new LinkedHashMap<>();
        snippets.put("type", "array");
        snippets.put("minItems", 1);
        snippets.put("maxItems", MAX_SNIPPETS);
        snippets.put("items", Map.of(
                "type", "string",
                "minLength", MIN_SNIPPET_LENGTH,
                "maxLength", MAX_SNIPPET_LENGTH));

        Map<String, Object> schema = new LinkedHashMap<>();
        schema.put("type", "object");
        schema.put("properties", Map.of("snippets", snippets));
        schema.put("required", List.of("snippets"));
        return schema;
    }
}
